package tools.kaiju.gradlezilla.generator

class DockerfileGenerator {
    fun generate(spec: GeneratorSpec): Dockerfile =
        Dockerfile(
            layers =
                listOf(
                    headerComment(spec),
                    baseImage(spec),
                    envVars(spec),
                    cmdlineTools(spec),
                    sdkPackages(spec),
                    gradleWrapper(),
                    dependencyResolution(spec),
                    build(),
                ),
        )

    // ── L1: Base image ───────────────────────────────────────────────────

    private fun headerComment(spec: GeneratorSpec) =
        DockerLayer {
            buildString {
                appendLine("# Generated by gradlezilla")
                appendLine("#")
                appendLine("#   compileSdk:    ${spec.androidSdkVersion}")
                appendLine("#   buildTools:    ${spec.androidPlatformToolsVersion}")
                appendLine("#   jdk:           ${spec.jdkVersion}")
                spec.gradleVersion?.let { appendLine("#   gradle:        $it") }
                spec.androidNdkVersion?.let { appendLine("#   ndk:           $it") }
                spec.modules.forEach { m ->
                    appendLine("#   module:        ${m.path} (${if (m.isApplication) "app" else "lib"})")
                }
            }
        }

    private fun baseImage(spec: GeneratorSpec) =
        DockerLayer {
            """
            # ── L1: Base JDK ─────────────────────────────────────────────────
            FROM eclipse-temurin:${spec.jdkVersion}-jdk-jammy AS base
            """.trimIndent() + "\n"
        }

    private fun envVars(spec: GeneratorSpec) =
        DockerLayer {
            buildString {
                appendLine("ENV ANDROID_HOME=/opt/android-sdk \\")
                appendLine("    ANDROID_SDK_ROOT=/opt/android-sdk \\")
                appendLine("    GRADLE_OPTS=\"-Dorg.gradle.daemon=false\"")
                appendLine()
                appendLine("ENV PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools")
                spec.gradleJvmArgs?.let { args ->
                    appendLine()
                    appendLine("# JVM args from gradle.properties")
                    appendLine("ENV GRADLE_OPTS=\"\$GRADLE_OPTS $args\"")
                }
            }
        }

    // ── L2: cmdline-tools (changes ~yearly) ──────────────────────────────

    private fun cmdlineTools(spec: GeneratorSpec) =
        DockerLayer {
            val steps =
                listOf(
                    "apt-get update -qq",
                    "apt-get install -yqq --no-install-recommends curl unzip git",
                    "rm -rf /var/lib/apt/lists/*",
                    "mkdir -p \$ANDROID_HOME/cmdline-tools",
                    "curl -sSfL " +
                        "\"https://dl.google.com/android/repository/" +
                        "commandlinetools-linux-${spec.androidCommandLineToolsVersion}_latest.zip\" " +
                        "-o /tmp/cmdline-tools.zip",
                    "unzip -q /tmp/cmdline-tools.zip -d \$ANDROID_HOME/cmdline-tools",
                    "mv \$ANDROID_HOME/cmdline-tools/cmdline-tools \$ANDROID_HOME/cmdline-tools/latest",
                    "rm /tmp/cmdline-tools.zip",
                )
            buildString {
                appendLine("# ── L2: Android command-line tools ───────────────────────────────")
                appendLine("RUN ${steps.joinToString(" \\\n    && ")}")
            }
        }

    // ── L3: SDK packages (changes per compileSdk/NDK bump) ───────────────

    private fun sdkPackages(spec: GeneratorSpec) =
        DockerLayer {
            val packages =
                buildList {
                    add("platforms;android-${spec.androidSdkVersion}")
                    add("platform-tools")
                    add("build-tools;${spec.androidPlatformToolsVersion}")
                    spec.androidNdkVersion?.let { add("ndk;$it") }
                    spec.androidCmakeVersion?.let { add("cmake;$it") }
                }

            buildString {
                appendLine("# ── L3: SDK packages ─────────────────────────────────────────────")
                appendLine("RUN yes | sdkmanager --licenses > /dev/null 2>&1 \\")
                append("    && sdkmanager --install")
                packages.forEach { pkg ->
                    appendLine(" \\")
                    append("       \"$pkg\"")
                }
                appendLine()
            }
        }

    // ── L4: Gradle wrapper (changes per wrapper upgrade) ─────────────────

    private fun gradleWrapper() =
        DockerLayer {
            """
            # ── L4: Gradle wrapper ───────────────────────────────────────────
            # Cached until gradle-wrapper.properties changes.
            WORKDIR /app
            COPY gradle/wrapper/ gradle/wrapper/
            COPY gradlew ./
            RUN --mount=type=cache,target=/root/.gradle/wrapper \
                chmod +x gradlew \
                && ./gradlew --version
            """.trimIndent() + "\n"
        }

    // ── L5: Dependency resolution (changes per dep change) ───────────────

    private fun dependencyResolution(spec: GeneratorSpec) =
        DockerLayer {
            buildString {
                appendLine("# ── L5: Dependency resolution (BuildKit cache-mounted) ───────────")
                appendLine("# Build files only — deps cached separately from source changes.")
                appendLine("COPY build.gradle* settings.gradle* gradle.properties* ./")
                appendLine("COPY gradle/libs.versions.toml* gradle/")

                if (spec.hasBuildSrc) {
                    appendLine()
                    appendLine("# buildSrc is compiled before dependency resolution")
                    appendLine("COPY buildSrc/ buildSrc/")
                }
                if (spec.hasBuildLogic) {
                    appendLine()
                    appendLine("# Convention plugins needed for settings evaluation")
                    appendLine("COPY build-logic/ build-logic/")
                }

                val modules = spec.modules
                if (modules.size > 1 || (modules.size == 1 && modules[0].dir != "app")) {
                    appendLine()
                    appendLine("# Per-module build files for dependency resolution")
                    modules.forEach { m -> appendLine("COPY ${m.dir}/build.gradle* ${m.dir}/") }
                }

                appendLine()
                appendLine("RUN --mount=type=cache,target=/root/.gradle/caches \\")
                appendLine("    --mount=type=cache,target=/root/.gradle/wrapper \\")
                appendLine("    ./gradlew dependencies --no-configuration-cache || true")
            }
        }

    // ── L6: Full build (changes every commit) ────────────────────────────

    private fun build() =
        DockerLayer {
            """
            # ── L6: Build ────────────────────────────────────────────────────
            COPY . .
            RUN --mount=type=cache,target=/root/.gradle/caches \
                --mount=type=cache,target=/root/.gradle/wrapper \
                ./gradlew assembleRelease --no-configuration-cache
            """.trimIndent() + "\n"
        }
}
